# Generated by Django 2.1.4 on 2019-03-20 17:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=45)),
                ('tipo_locale', models.CharField(choices=[('FREE', 'Gratis'), ('CONS', 'Previa consumazione'), ('PAY', 'A pagamento')], default='FREE', max_length=4)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=15)),
                ('sitoweb', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Presa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, default='', max_length=250)),
                ('path_foto', models.ImageField(blank=True, default='', upload_to='foto_prese/')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prese', to='PowerZoneAPI.Locale')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('testo', models.CharField(max_length=250)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='PowerZoneAPI.Locale')),
                ('recensore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='presa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PowerZoneAPI.TipoPresa'),
        ),
    ]
