# Generated by Django 2.1.4 on 2019-01-02 14:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('tipo_locale', models.CharField(choices=[('FREE', 'Gratis'), ('CONS', 'Previa consumazione'), ('PAY', 'A pagamento')], default='FREE', max_length=4)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('email', models.EmailField(blank=True, default='aa@example.it', max_length=100)),
                ('telefono', models.CharField(blank=True, default='telDefault', max_length=15)),
                ('sitoweb', models.URLField(blank=True, default='powerzone.com')),
            ],
        ),
        migrations.CreateModel(
            name='Presa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_presa', models.CharField(choices=[('PR16', 'Presa elettrica grande'), ('PR10', 'Presa elettrica piccola'), ('PRSC', 'Presa Schuko'), ('PRU2', 'Presa USB'), ('PRU3', 'Presa USB 3.0'), ('PRAU', 'Presa auto elettrica')], max_length=4)),
                ('descrizione', models.CharField(blank=True, default='descrizione', max_length=250)),
                ('path_foto', models.ImageField(blank=True, default='foto_prese/%Y-%m-%d-%H-%M-%S.jpg', upload_to='foto_prese/')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prese', to='PowerZoneAPI.Locale')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('voto', models.IntegerField()),
                ('testo', models.CharField(max_length=250)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='PowerZoneAPI.Locale')),
            ],
        ),
    ]
