# Generated by Django 2.1.4 on 2019-01-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZoneAPI', '0002_auto_20190102_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='locale',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='locale',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='presa',
            name='descrizione',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='presa',
            name='path_foto',
            field=models.ImageField(blank=True, default='', upload_to='foto_prese/'),
        ),
    ]
