# Generated by Django 2.1.4 on 2019-01-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZoneAPI', '0003_auto_20190102_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='sitoweb',
            field=models.URLField(blank=True, default=''),
        ),
    ]
