# Generated by Django 2.1.4 on 2019-05-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZoneAPI', '0004_auto_20190514_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoPresa',
        ),
    ]
